# Generated by Django 4.2.16 on 2024-12-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='job',
            field=models.ForeignKey(default=0, help_text='The job associated with this image', on_delete=django.db.models.deletion.CASCADE, related_name='job_images', to='myappLubd.job'),
            preserve_default=False,
        ),
    ]
