# Generated by Django 4.2.16 on 2024-11-29 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappLubd', '0003_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='users',
            field=models.ManyToManyField(related_name='accessible_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='myappLubd.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='myappLubd_r_room_ty_90b2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='myappLubd_r_is_acti_767b23_idx'),
        ),
    ]
