# Generated by Django 4.2.16 on 2024-11-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0004_property_users_userprofile_properties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='positions',
        ),
    ]
