# Generated by Django 4.2.16 on 2024-11-30 13:04

import django.core.validators
from django.db import migrations, models
import myappLubd.models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0005_rename_bio_userprofile_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=myappLubd.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_job_images/%Y/%m/webp/'),
        ),
    ]
