# Generated by Django 4.2.16 on 2024-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0006_jobimage_original_image_alter_jobimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remarks',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
