# Generated by Django 4.2.16 on 2024-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0007_job_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='myappLubd.property'),
        ),
    ]
