# Generated by Django 4.2.16 on 2024-12-05 11:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappLubd', '0008_remove_property_rooms_room_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Job Image', 'verbose_name_plural': 'Job Images'},
        ),
        migrations.AddField(
            model_name='jobimage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail version of the image', null=True, upload_to='maintenance_job_images/%Y/%m/thumbnails/'),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the image', null=True),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, help_text='WebP converted version of the image', null=True, upload_to='maintenance_job_images/%Y/%m/webp/'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='name',
            field=models.CharField(help_text='Name of the image', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='original_image',
            field=models.ImageField(blank=True, help_text='Original uploaded image file', null=True, upload_to='maintenance_job_images/originals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the image was uploaded'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_job_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
