# Generated by Django 4.2.16 on 2024-12-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0009_alter_jobimage_options_jobimage_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='thumbnail',
        ),
    ]
