# Generated by Django 4.2.16 on 2024-12-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0010_remove_jobimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='jobimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='jobimage',
            name='width',
        ),
    ]
