# Generated by Django 4.2.16 on 2024-12-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0012_remove_jobimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='name',
        ),
    ]
