# Generated by Django 4.2.16 on 2024-12-05 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0013_remove_jobimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='original_image',
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image file', null=True, upload_to='maintenance_job_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
    ]
