# Generated by Django 4.2.16 on 2024-12-05 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0015_alter_jobimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image file', null=True, upload_to='maintenance_job_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
    ]
