# Generated by Django 4.2.16 on 2024-12-05 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0016_jobimage_file_size_jobimage_height_jobimage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='jobimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='jobimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jobimage',
            name='width',
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Original uploaded image file', null=True, upload_to='maintenance_job_images/originals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
    ]
